[project]
name = "awesome-threat-detection"
version = "0.1.0"
description = "A curated list of resources about detecting threats and defending applications as well as Linux and Kubernetes systems."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.7.0",
]
